stolostron/search-indexer

pkg/config/config_development.go
pkg/database/connection.go
pkg/database/connection_test.go

Fixes some bugs introduced by PR #27 
- Reload config after initializing dev mode.
- Add CASCADE when dropping the search schema.
- Add IF NOT EXIST when creating indexes

Fix bugs from merging PR #27

---

pkg/database/batch.go
pkg/database/dataValidation.go
pkg/database/resync.go
pkg/database/resync_test.go
pkg/database/sync.go
pkg/database/sync_test.go
pkg/server/syncHandler.go
pkg/server/syncHandler_test.go
pkg/server/testHelper_test.go

Issue: https://github.com/stolostron/backlog/issues/17972
- SyncResponse includes total resources and edges.
- SyncResponse includes errors when applicable.

Respond with total items and errors.

---

Makefile

**Related Issue:**  stolostron/backlog#19286
- Update makefile to automatically discover the search-indexer route on the current target cluster when running Locust.
- Matches the Makefile for search-v2-api.

Locust test discover route to current target cluster

---

sonar-project.properties

Project key on sonar is open-cluster-management.
sonar-presubmit-job will fail because of the mismatch.
See slack discussion: https://coreos.slack.com/archives/CSZLMKPS5/p1657768166877289

fix sonar project key - rename to open-cluster-management

---

pkg/clustersync/clusterSync.go
pkg/clustersync/clusterSync_test.go

**Related Issue:**  stolostron/backlog#22013
Add apigroup and kind_plural for clusters to match managedclusterinfos - for rbac filtering

update cluster rbac

---

Makefile

**Related Issue:**  N/A
- Fixes problem where make hangs when oc is not connected to a cluster.

Fixes make command seems unresponsive

---

pkg/database/upsertCluster.go

Fix error: E1024 21:17:13.824456       1 connection.go:119] Error deleting resources from search.resources for clusterName remote-1. expected 0 arguments, got 1

fix delete cluster issue

---

pkg/database/dataValidation.go
pkg/database/dataValidation_test.go

**Related Issue:**  https://github.com/stolostron/backlog/issues/27063
The previous PR #73 added the cluster column to the cluster pseudo-node, this affected the validation logic. With this change we'll ignore this node in the resource counts.

Ignore the cluster pseudo-node when validating resources

---

pkg/clustersync/clusterSync.go
pkg/clustersync/clusterSync_test.go

**Related Issue:**  https://issues.redhat.com/browse/ACM-2671
- Add property `adddon` to Cluster pseudo-node. It tracks the enabled addons.

Track enabled addons for disabled cluster message

---

pkg/config/config.go
pkg/server/requestLimiter.go

**Related Issue:**  https://issues.redhat.com/browse/ACM-3065
Fixes the following error introduced by the previous PR.
```
goroutine 283 [running]:
runtime.throw({0x19770b7?, 0x20?})
runtime/panic.go:992 +0x71 fp=0xc00172f7e0 sp=0xc00172f7b0 pc=0x437111
runtime.mapaccess2_faststr(0x6?, 0x7f00ff9909f0?, {0xc0007b19fa, 0x8})
runtime/map_faststr.go:117 +0x3d4 fp=0xc00172f848 sp=0xc00172f7e0 pc=0x412ff4
github.com/stolostron/search-indexer/pkg/server.requestLimiterMiddleware.func1({0x1bb1f60, 0xc000773dc0}, 0xc0008eee40?)
github.com/stolostron/search-indexer/pkg/server/requestLimiter.go:28 +0x197 fp=0xc00172f948 sp=0xc00172f848 pc=0x159fff7
net/http.HandlerFunc.ServeHTTP(0xc000daf600?, {0x1bb1f60?, 0xc000773dc0?}, 0x793bf4?)
```

ACM-3065 Fixes lock problem in requestLimiter

---

pkg/database/connection.go
pkg/database/connection_test.go

**Related Issue:**  https://issues.redhat.com/browse/ACM-3265
- Add a new index on search.edges for the cluster key. This index greatly improves efficiency of the sync validation logic.
- Add missing index for search.edges. These were created only from the operator.

ACM-3265 Add index to resolve CPU issues

---

Makefile
Makefile.prow
pkg/clustersync/clusterSync_test.go
pkg/database/batch.go
pkg/database/connection_test.go
pkg/database/dataValidation.go
pkg/database/dataValidation_test.go
pkg/database/resync.go
pkg/database/resync_test.go
pkg/database/sync.go
pkg/database/sync_test.go
pkg/database/upsertCluster_test.go
pkg/server/syncHandler.go

https://issues.redhat.com/browse/ACM-5168
- Use the context from incoming http request for the DB queries associated with the request. With this we can ensure that if the request is cancelled, the database queries triggered by it also get cancelled.

ACM-5168: Propagate context from incoming requests

---

pkg/database/batch.go
pkg/database/batch_test.go
pkg/database/dataValidation.go
pkg/database/dataValidation_test.go
pkg/database/resync.go
pkg/database/resync_test.go
pkg/database/sync.go
pkg/database/sync_test.go
pkg/database/testHelper_test.go
pkg/server/syncHandler.go
pkg/server/syncHandler_test.go
pkg/server/testHelper_test.go

https://issues.redhat.com/browse/ACM-5168
- Respond with error if resync is unable to delete existing data in postgres.
- Respond with error if a batch operation fails because "failed to connect".
- Respond with error if unable to get the resource totals for validation.

ACM-5168: Improve handling of errors from database

---

pkg/config/config.go

https://issues.redhat.com/browse/ACM-5899
- **Reduced `DB_MAX_CONNS` from 20 to 10.** 
- Should reduce memory usage because idle connections consume memory on postgres and indexer pods.
- I haven't noticed a performance impact from reducing these connections.
- **Increased `DB_BATCH_SIZE` from 500 to 2500.** 
- With a larger batch size, less connections are required. With this change only 2 connections are used to process a request to add 5,000 resources. Without this it would use 10 connections.
- **Increased `DB_MIN_CONNS` from 0 to 2.**
- Reduces the time needed to process the first request.
- **Reduced `REQUEST_LIMIT` from 50 to 25.**
- Reduces the max memory needed to process all concurrent requests.
- Increases the chances that an individual requests will complete without timing …

ACM-5899: Update default env config values

---

pkg/config/config.go

https://issues.redhat.com/browse/ACM-7320
- Reduce the default REQUEST_LIMIT to 20.
- The more conservative request limit helps reduce errors and memory problems on the indexer. By reducing the number of concurrent requests we have much better chances that the accepted requests will complete fast.
A similar change has been merged for release-2.8 and main.
- #111 
- #109

[release-2.7] ACM-7320: Reduce default REQUEST_LIMIT to 20

---

Dockerfile

N/A
- Restore konflux update, merge to `main` instead of `release-2.12`. Merging to release branch breaks the fast-forward.
- PR #139

Restore konflux PR#139 (main)

---

pkg/config/config.go
pkg/server/largeRequestLimiter.go
pkg/server/largeRequestLimiter_test.go
pkg/server/server.go

https://issues.redhat.com/browse/ACM-0000](https://issues.redhat.com/browse/ACM-16129
- Added large request limiter middleware to limit the number of large requests being processed to help control memory spikes from large requests.

ACM-16129: large request limiter middleware to limit too many large requests

---

pkg/server/largeRequestLimiter.go

- Fixed large request limiter bug. Referenced wrong variable, LargeRequestLimit instead of LargeRequestSize when comparing against incoming requests.

fix large request limiter

---

pkg/config/config.go

https://issues.redhat.com/browse/ACM-13201
- Reduce the Postgres connection lifetime to **5 minutes**.
- This helps release memory used by the Postgres pod for the connection caches.
Note: This **doesn't disable the statement cache** to avoid other performance issues.

ACM-13201: Reduce postgres connection lifetime

---

Dockerfile.rhtap

N/A
- Fix incorrect image label merged with #362

[release-2.13] Fix incorrect label in Dockerfile.rhtap

---

.tekton/search-indexer-acm-211-pull-request.yaml

- Added image-digest and image-url params to fix failures on https://github.com/stolostron/search-indexer/pull/396

[release-2.11] fix sast-snyk-check missing image-digest and image-url

---

.tekton/search-indexer-acm-210-pull-request.yaml

- cherry-pick of https://github.com/stolostron/search-indexer/pull/410/files to fix konflux failures

[release-2.10] fix sast-snyk-check missing image-digest and image-url

---

pkg/database/resync.go
pkg/database/resync_test.go
pkg/testutils/mockDatabaseState.go

https://issues.redhat.com/browse/ACM-20720
- Handles the DB state when local-cluster gets renamed by:
1. checking if cluster resync request contains a hub cluster resource by checking properties for _hubClusterResource
2. queries for all distinct cluster names
3. if clusters exist that don't match the incoming hubClusterResource cluster, delete them

ACM-20720 handle db state after local-cluster rename

---

pkg/database/resync.go

Previously, the `upsertResources` function could repeatedly decode items into the same resource, and then insert that updated resource into the database. Fields from the new item would overwrite existing fields in the resource, but it would not remove the fields that were not set in the new item, causing incorrect data to accumulate in some resources.
Now the resource is reset before decoding.
Refs:
- https://issues.redhat.com/browse/ACM-21047
https://issues.redhat.com/browse/ACM-21047
- Fix accidental data accumulation in resources

Fix accidental data accumulation

---

pkg/database/resync.go
pkg/database/resync_test.go
pkg/testutils/mockDatabaseState.go

- Fixed SQL for selecting distinct cluster names on the hub cluster when checking for hub cluster rename. A resource of kind Cluster for each cluster exists on the hub cluster, we missed explicitly exempting that condition in the SQL. This led to each resync request triggering a hub cluster cleanup

resync request hub cluster rename check incorrect sql
