README.md

locust instructions for running without ui was missing filename in command

fix for locust instructions

---

Makefile
Makefile.prow
README.md
go.mod
pkg/database/connection.go
pkg/database/resync_test.go
pkg/database/sync_test.go
pkg/database/testHelper_test.go
pkg/server/syncHandler_test.go
pkg/server/testHelper_test.go

Fixes lint errors so we can start enforcing from prow build.

Enable lint and fix initial errors

---

pkg/database/connection.go
pkg/database/connection_test.go

Reverts stolostron/search-indexer#11
Data won't load in edges table without reverting this.

Revert "primary key edges table"

---

go.mod
pkg/database/connection.go
pkg/database/connection_test.go
pkg/database/resync.go
pkg/database/resync_test.go
pkg/database/sync.go
pkg/server/syncHandler.go
sonar.project.properties

Create search schema to add tables

Create search schema to add tables

---

Makefile
Makefile.prow
pkg/database/connection.go
pkg/database/connection_test.go
pkg/database/sync.go

- Add `gosec` check.
- Fix missing error checks from gosec.

Check for errors (gosec)

---

sonar-project.properties

- Exclude test code and main.go from coverage reporting.

Update sonar coverage reporting

---

benchmark.md
pkg/database/connection.go
pkg/database/connection_test.go
pkg/database/sync.go
pkg/model/model.go

Creating jsonb index on data keys and benchmarks

Add jsonb indexing for kind, name, and namespace

---

pkg/config/config.go
pkg/database/batch.go
pkg/database/connection.go
pkg/database/mocks/simple.json
pkg/database/resync_test.go
pkg/database/sync_test.go
pkg/database/testHelper_test.go
pkg/server/syncHandler.go

Issue: https://github.com/stolostron/backlog/issues/17972
- Adds tests for response contents.
- Resolve several coded smells reported by Sonarcloud.

Add tests for response content

---

pkg/clustersync/clusterSync.go
pkg/clustersync/leaderElection.go
pkg/clustersync/leaderElection_test.go
pkg/clustersync/testHelper_test.go
pkg/database/connection.go
pkg/database/testHelper_test.go
pkg/database/upsertCluster.go

Issue: https://github.com/stolostron/backlog/issues/20264

Update leader election tests

---

pkg/clustersync/clusterSync.go

fix addon delete

---

pkg/clustersync/clusterSync.go
pkg/clustersync/clusterSync_test.go
pkg/database/upsertCluster.go

Add filter to informer to only watch search-collector addon events

---

pkg/database/connection.go
pkg/database/connection_test.go

https://github.com/stolostron/backlog/issues/15197

Add create view statement for relations

---

pkg/database/connection.go

**Related Issue:**  stolostron/backlog#21297
- Use SSL when connecting to Postgres

Require SSL on Postgres connection

---

test/cluster-template.json

This will add a cluster node with the same name as the load.

add cluster resource to the load in locust

---

pkg/database/connection.go
pkg/database/connection_test.go
pkg/database/sync.go

**Related Issue:**  stolostron/backlog#<ISSUE_NUMBER>https://github.com/stolostron/backlog/issues/22510

Add column kind_plural to resource table

---

test/locust-clusters.py

Add real SNO cluster data for locust test

Add sno cluster data for locust test

---

pkg/database/connection.go
pkg/database/connection_test.go
pkg/database/sync.go

This reverts commit 5e668fb82299467817ba3db15eb995f163b6aa59.

Revert "Add column kind_plural to resource table (#55)"

---

README.md
pkg/database/connection.go
pkg/database/connection_test.go
pkg/database/dataValidation.go
pkg/database/sync.go

**Related Issue:**  https://github.com/stolostron/backlog/issues/24475

remove view from indexer

---

OWNERS
README.md

**Related Issue:**  https://github.com/stolostron/backlog/issues/24878

Update OWNERS and trigger prow to publish 2.7

---

README.md

Signed-off-by: dislbenn <dbennett@redhat.com>
**Related Issue:**  stolostron/backlog#25961
Triggering image rebuild.

[release-2.7] Triggering image rebuild

---

pkg/database/resync.go
pkg/database/resync_test.go

**Related Issue:**  N/A
- Update comments about implementation choices on resync.go

Refactor to cleanup resync.go file

---

pkg/clustersync/clusterSync.go
pkg/clustersync/clusterSync_test.go

**Related Issue:**  stolostron/backlog#25996
https://github.com/stolostron/backlog/issues/25996#issuecomment-1267108973

add _hubClusterResource property to cluster node

---

pkg/clustersync/clusterSync_test.go
pkg/database/dataValidation.go
pkg/database/dataValidation_test.go
pkg/database/resync.go
pkg/database/resync_test.go
pkg/database/testHelper_test.go
pkg/database/upsertCluster.go
pkg/database/upsertCluster_test.go

Rewrite database queries in goqu.
Continuation of https://github.com/stolostron/search-indexer/pull/67

Rewrite queries in goqu - 2

---

pkg/database/connection.go
pkg/database/connection_test.go

Signed-off-by: Xavier Dharmaiyan <xavier@redhat.com>

added index checks

---

pkg/clustersync/clusterSync_test.go
pkg/database/resync_test.go
pkg/database/upsertCluster.go
pkg/database/upsertCluster_test.go

**Related Issue:**  https://issues.redhat.com/browse/ACM-2426
Add cluster property to cluster nodes.

fix cluster count

---

pkg/config/config.go
pkg/database/connection.go

**Related Issue:**  https://issues.redhat.com/browse/ACM-3071

update max connections to 30

---

pkg/server/requestLimiter.go

**Related Issue:**  ACM-3065
Fix code bug while locking map.

ACM-3065 Fix another lock problem in requestLimiter.go

---

OWNERS
go.mod
pkg/config/config.go
pkg/database/connection.go
pkg/database/connection_test.go
pkg/database/resync.go
pkg/database/sync.go
pkg/metrics/slowLog.go
pkg/server/healthProbes.go
pkg/server/requestLimiter.go
pkg/server/requestLimiter_test.go
pkg/server/server.go
pkg/server/syncHandler.go

- https://issues.redhat.com/browse/ACM-3065
- https://issues.redhat.com/browse/ACM-3071
- https://issues.redhat.com/browse/ACM-3265
Merge fixes for ACM-3065, ACM-3071, and ACM-3265 into `release-2.7` to be included for 2.7.1

[release-2.7] Cherry-pick fixes for ACM-3065, ACM-3071, and ACM-3265

---

.github/pull_request_template.md
pkg/clustersync/clusterSync.go
pkg/clustersync/clusterSync_test.go
pkg/config/config.go

**Related Issue:**  N/A
- Update PR template
- Tidy up code

Update PR template and tidy up code

---

pkg/clustersync/clusterSync.go
pkg/database/sync.go

https://issues.redhat.com/browse/ACM-5168
- Use is distinct from clause to check if data is changed (https://stackoverflow.com/questions/57144253/on-conflict-update-if-json-value-is-different-in-postgresql)

ACM-5168 add on conflict clause

---

Dockerfile
go.mod

https://issues.redhat.com/browse/ACM-5513
- Upgrade go to v1.20

ACM-5513: Upgrade to go v1.20

---

Dockerfile
Makefile
Makefile.prow
go.mod

https://issues.redhat.com/browse/ACM-5513
- Update go to v1.20

[release-2.7] ACM-5513 Update go to v1.20

---

pkg/clustersync/clusterSync.go
pkg/clustersync/clusterSync_test.go

- Updated _hubClusterResource to boolean value instead of text when creating cluster nodes.

update _hubClusterResource to bool in cluster nodes

---

pkg/database/goquHelper.go
pkg/database/resync.go
pkg/database/resync_test.go
pkg/database/sync.go
pkg/database/testHelper_test.go
pkg/database/upsertCluster.go
pkg/database/upsertCluster_test.go
pkg/metrics/slowLog.go
pkg/server/syncHandler.go
pkg/server/syncHandler_test.go
pkg/testutils/mockBatchResults.go
pkg/testutils/mockDatabaseState.go

[release-2.8] Reimplement resync logic

---

pkg/database/goquHelper.go
pkg/database/goquHelper_test.go

- Copied from https://github.com/stolostron/search-indexer/pull/116/files

[release-2.9]  Fix Lint - Add param count validation for goqu

---

pkg/clustersync/clusterSync.go
pkg/clustersync/clusterSync_test.go

https://issues.redhat.com/browse/ACM-14658
- Collect the `apiEndpoint` property for the Cluster resource.

ACM-14658 Collect apiEndpoint property for the Cluster resource

---

pkg/config/config.go
pkg/database/connection.go

Fix gosec errors converting to int32

---

renovate.json

- Changed konflux run schedule from 8am every Tuesday to 8am 1st of every month.

update konflux run times

---

.tekton/search-indexer-acm-213-pull-request.yaml
.tekton/search-indexer-acm-213-push.yaml
Dockerfile

N/A
- Merge release-2.13 into main to fix fast-forward.

Merge konflux updates from release-2.13 to main

---

.tekton/search-indexer-acm-211-pull-request.yaml
.tekton/search-indexer-acm-211-push.yaml

**Related Issue:**  https://github.com/konflux-ci/build-definitions/blob/main/task/buildah/0.3/MIGRATION.md
- Update konflux config

[release-2.11] Update Konflux config

---

.tekton/search-indexer-acm-210-pull-request.yaml
.tekton/search-indexer-acm-210-push.yaml

**Related Issue:**  https://github.com/konflux-ci/build-definitions/blob/main/task/buildah/0.3/MIGRATION.md
- Update konflux config

[release-2.10] Update Konflux config

---

.ci-operator.yaml
Dockerfile
Dockerfile.rhtap
Makefile
go.mod

https://issues.redhat.com/browse/ACM-18716
- Go 1.23
- UBI 9

ACM-18716 Update to Go 1.23 and UBI 9

---

Dockerfile
Dockerfile.rhtap
Makefile
Makefile.prow
go.mod
go.sum

Manual cherry-pick of https://github.com/stolostron/search-indexer/pull/267

release 2.12 ACM-18716 Update to go1.22 (#267)

---

.ci-operator.yaml
Dockerfile
Dockerfile.rhtap
Makefile
go.mod

cherry-pick of https://github.com/stolostron/search-indexer/pull/269

2.13 ACM-18716 Update to Go 1.23 and UBI 9 (#269)

---

.ci-operator.yaml
Dockerfile
Dockerfile.rhtap
Makefile
go.mod

cherry-pick of https://github.com/stolostron/search-indexer/pull/269

[release-2.12] go 123 ubi 9

---

.ci-operator.yaml
Dockerfile
Dockerfile.rhtap
Makefile
Makefile.prow
go.mod

- Added .ci-operator.yaml file to make prow happy
- Updated Go to 1.23

[release-2.11] update go to 1.23

---

.ci-operator.yaml
Dockerfile
Dockerfile.rhtap
Makefile
Makefile.prow
go.mod

- Added .ci-operator.yaml and upgraded go to 1.23

[release-2.10] update go to 1.23

---

.ci-operator.yaml
Dockerfile
Makefile
Makefile.prow
go.mod

- Added .ci-operator.yaml and updated go to 1.23

[release 2.9] update go to 1.23

---

.tekton/search-indexer-acm-214-pull-request.yaml
.tekton/search-indexer-acm-214-push.yaml
Dockerfile
Dockerfile.rhtap
renovate.json

N/A
- [Enabling hermetic builds in Konflux](https://konflux.pages.redhat.com/docs/users/building/hermetic-builds.html)
- [Prefetching package manager dependencies for hermetic builds](https://konflux.pages.redhat.com/docs/users/building/prefetching-dependencies.html)
- Updates renovate.json

Enable konflux hermetic builds

---

.tekton/search-indexer-acm-214-pull-request.yaml

- Added image-digest param to fix https://github.com/stolostron/search-indexer/pull/367

add image-digest value for sast-coverity-check-oci-ta

---

.tekton/search-indexer-acm-211-pull-request.yaml

- moved image-digest and image-url params according to https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1745404637499059?thread_ts=1745339419.829389&cid=C04PZ7H0VA8

[release-2.11] fix sast-snyk-check params

---

.tekton/search-indexer-acm-214-push.yaml

Fix konflux on-push config

---

.tekton/search-indexer-acm-211-push.yaml

[release-2.11] Fix konflux on-push config

---

.tekton/search-indexer-acm-210-push.yaml

[release-2.10] Fix konflux on-push config

---

.tekton/search-indexer-acm-214-pull-request.yaml
.tekton/search-indexer-acm-214-push.yaml

Manually cherry-picked https://github.com/stolostron/search-indexer/pull/426/files to main

Update Konflux references (#426) (Manually)

---

pkg/clustersync/clusterSync.go
pkg/clustersync/clusterSync_test.go
pkg/database/upsertCluster.go
pkg/database/upsertCluster_test.go
pkg/server/requestLimiter.go

https://issues.redhat.com/browse/ACM-20492
- Removed hard-coded local-cluster.

ACM-20492 remove hard-coded local-cluster

---

.github/scripts/auto_review.py
.github/workflows/auto_code_review.yml

Adding a worflow to trigger automatic code review. This requires adding a secret called OPENAI_API_KEY. I can add mine if I am allowed the permission.
Henceforth, whenever a PR is opened, synchronize, reopened this bot will be called in and code review will be run. This can also be run manually anytime under Actions tab.

Adding automatic pr review

---

.github/renovate.json

Reduce go package update PRs

---

.tekton/search-indexer-acm-214-pull-request.yaml

N/A
- Update konflux to run on PRs to release-2.14

[release-2.14] Update konflux to run on PRs to release-2.14

---

.tekton/search-indexer-acm-210-pull-request.yaml
.tekton/search-indexer-acm-210-push.yaml

- migration https://github.com/konflux-ci/build-definitions/blob/main/task/source-build/0.3/MIGRATION.md

[release-2.10] build-source-image param migration

---

.tekton/search-indexer-acm-215-pull-request.yaml
.tekton/search-indexer-acm-215-push.yaml

- Added hermetic build, multi-arch, and other params back that konflux missed with the 2.15 config

[main] apply params, hermetic, multi-arch

---

.tekton/search-indexer-acm-211-pull-request.yaml
.tekton/search-indexer-acm-211-push.yaml
Dockerfile
Dockerfile.rhtap

- Added multi arch and hermetic builds

[release-2.11] multi arch and hermetic builds

---

.ci-operator.yaml
Dockerfile
Dockerfile.rhtap
go.mod

[release-2.12] update go to 1.24 (#619)

---

.ci-operator.yaml
Dockerfile
Dockerfile.rhtap
go.mod

[release-2.11] update go to 1.24 (#619)
